In [1]:
import pandas as pd
import numpy as np

In [ ]:
df =  pd.read_csv(r"E:\Walmart\walmart_clean.csv")

In [4]:
df

,INVOICE_ID,BRANCH,CITY,CATEGORY,UNIT_PRICE,QUANTITY,DATE,TIME,PAYMENT_METHOD,RATING,PROFIT_MARGIN,TOTAL
0,1,WALM003,San Antonio,Health and beauty,74.69,7,05/01/19,13:08:00,Ewallet,9.1,0.48,3.36
1,2,WALM048,Harlingen,Electronic accessories,15.28,5,08/03/19,10:29:00,Cash,9.6,0.48,2.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7,03/03/19,13:23:00,Credit card,7.4,0.33,2.31
3,4,WALM064,Bedford,Health and beauty,58.22,8,27/01/19,20:33:00,Ewallet,8.4,0.33,2.64
4,5,WALM013,Irving,Sports and travel,86.31,7,08/02/19,10:37:00,Ewallet,5.3,0.48,3.36
...,...,...,...,...,...,...,...,...,...,...,...,...
9964,9996,WALM056,Rowlett,Fashion accessories,37.00,3,03/08/23,10:10:00,Cash,3.0,0.33,0.99
9965,9997,WALM030,Richardson,Home and lifestyle,58.00,2,22/02/21,14:20:00,Cash,7.0,0.48,0.96
9966,9998,WALM050,Victoria,Fashion accessories,52.00,3,15/06/23,16:00:00,Credit card,4.0,0.48,1.44
9967,9999,WALM032,Tyler,Home and lifestyle,79.00,2,25/02/21,12:25:00,Cash,7.0,0.48,0.96
9968,10000,WALM069,Rockwall,Fashion accessories,62.00,3,26/09/20,09:48:00,Cash,3.0,0.33,0.99

In [5]:
df.head()

,INVOICE_ID,BRANCH,CITY,CATEGORY,UNIT_PRICE,QUANTITY,DATE,TIME,PAYMENT_METHOD,RATING,PROFIT_MARGIN,TOTAL
0,1,WALM003,San Antonio,Health and beauty,74.69,7,05/01/19,13:08:00,Ewallet,9.1,0.48,3.36
1,2,WALM048,Harlingen,Electronic accessories,15.28,5,08/03/19,10:29:00,Cash,9.6,0.48,2.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7,03/03/19,13:23:00,Credit card,7.4,0.33,2.31
3,4,WALM064,Bedford,Health and beauty,58.22,8,27/01/19,20:33:00,Ewallet,8.4,0.33,2.64
4,5,WALM013,Irving,Sports and travel,86.31,7,08/02/19,10:37:00,Ewallet,5.3,0.48,3.36

In [29]:
df.isnull()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
10046,False,False,False,False,False,False,False,False,False,False,False
10047,False,False,False,False,False,False,False,False,False,False,False
10048,False,False,False,False,False,False,False,False,False,False,False
10049,False,False,False,False,False,False,False,False,False,False,False
10050,False,False,False,False,False,False,False,False,False,False,False

In [61]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  bool
 1   Branch          10051 non-null  bool
 2   City            10051 non-null  bool
 3   category        10051 non-null  bool
 4   unit_price      10051 non-null  bool
 5   quantity        10051 non-null  bool
 6   date            10051 non-null  bool
 7   time            10051 non-null  bool
 8   payment_method  10051 non-null  bool
 9   rating          10051 non-null  bool
 10  profit_margin   10051 non-null  bool
dtypes: bool(11)
memory usage: 108.1 KB

In [57]:
df.duplicated().sum()

np.int64(0)

In [55]:
df.drop_duplicates(inplace=True)

In [60]:
df.dropna(inplace=True)

In [63]:
df.shape

(9969, 11)

In [8]:
df['TOTAL'] = df['UNIT_PRICE'] *  df['QUANTITY']

In [26]:
df.columns

Index(['INVOICE_ID', 'BRANCH', 'CITY', 'CATEGORY', 'UNIT_PRICE', 'QUANTITY',
       'DATE', 'TIME', 'PAYMENT_METHOD', 'RATING', 'PROFIT_MARGIN', 'SALES'],
      dtype='str')

In [31]:
df

,INVOICE_ID,BRANCH,CITY,CATEGORY,UNIT_PRICE,QUANTITY,DATE,TIME,PAYMENT_METHOD,RATING,PROFIT_MARGIN,TOTAL
0,1,WALM003,San Antonio,Health and beauty,74.69,7,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17
...,...,...,...,...,...,...,...,...,...,...,...,...
9964,9996,WALM056,Rowlett,Fashion accessories,37.00,3,03/08/23,10:10:00,Cash,3.0,0.33,111.00
9965,9997,WALM030,Richardson,Home and lifestyle,58.00,2,22/02/21,14:20:00,Cash,7.0,0.48,116.00
9966,9998,WALM050,Victoria,Fashion accessories,52.00,3,15/06/23,16:00:00,Credit card,4.0,0.48,156.00
9967,9999,WALM032,Tyler,Home and lifestyle,79.00,2,25/02/21,12:25:00,Cash,7.0,0.48,158.00
9968,10000,WALM069,Rockwall,Fashion accessories,62.00,3,26/09/20,09:48:00,Cash,3.0,0.33,186.00

In [30]:
df.rename(columns={'SALES': 'TOTAL'}, inplace=True)

In [99]:
df["UNIT_PRICE"] = df["UNIT_PRICE"].str.replace("$", "", regex=False)

In [96]:
df.columns= df.columns.str.upper()

In [32]:
df.to_csv("clean_walmart.csv", index=False)

In [33]:
import os
print(os.getcwd())

C:\Users\HP

In [82]:
import mysql.connector